### ISSUE TITLE
Project-2

### ISSUE THREAD

**Issue by Hodo-** [Hodo-/dsn1674-project-2#1]
@thomasjbradley I have two issues: 牛 — Ox and footer a:hoover.

1) 牛 — Ox is not aligned with others. I don't know why. Text-align includes all those tabs. I tried to make the text-align go left, but all the tabs remain centered for some reason. 

2) footer a:hoover is not responding to anything in css. I can't seem to get rid of the underline and make the font colour white.

**Comment by thomasjbradley** [comment]
_1:_

Here in the code:
https://github.com/Hodo-/project-2/blob/gh-pages/css/main.css#L78
There's a `text-align: center`—we probably want that to be `left`.

---

_2:_

The code needs to target the `footer a` directly, because it's the `a` tag that has the underline.

**Comment by Hodo-** [comment]
Thank you.

**Comment by Hodo-** [comment]
To be safe, is it okay to work in 382px? Or should I go lower like 320px?

**Comment by thomasjbradley** [comment]
It needs to go as low as 320px; that's what many smart phones are.
But you can work in what ever size you want, just you need to be constantly testing many widths between 320 px and 600 px.

**Comment by Hodo-** [comment]
Thank you.
